version: '3.8'

services:
  cep-weather:
    build:
      context: .
      dockerfile: Dockerfile
    image: cep-weather:latest
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    env_file:
      - .env
